# Generated by Django 5.0.10 on 2024-12-19 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_category_options_alter_recipe_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, help_text='Загрузите фотографию готового блюда', null=True, upload_to='recipes/', verbose_name='Фотография'),
        ),
    ]
